#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -eu

# Source app helpers
source /usr/share/yunohost/helpers

# This is a multi-instance app, meaning it can be installed several times independently
# The id of the app as stated in the manifest is available as $YNH_APP_ID
# The instance number is available as $YNH_APP_INSTANCE_NUMBER (equals "1", "2", ...)
# The app instance name is available as $YNH_APP_INSTANCE_NAME
#    - the first time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample
#    - the second time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample__2
#    - ynhexample__{N} for the subsequent installations, with N=3,4, ...
# The app instance name is probably what you are interested the most, since this is
# guaranteed to be unique. This is a good unique identifier to define installation path,
# db names, ...
app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$(ynh_app_setting_get $app domain)

# Get old parameter of the app
domain=$(ynh_app_setting_get $app domain)
path=$(ynh_app_setting_get $app path)
user=$(ynh_app_setting_get $app allowed_users)
is_public=$(ynh_app_setting_get $app is_public)
final_path=/var/www/$app

# Install dependency to convert tracks to a readable format for the browser
sudo apt-get update
sudo apt-get -y -qq install php5-sqlite

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path}"

if [ -d $final_path ]; then
    echo "There is already a directory: $final_path " | sudo tee /dev/stderr
    ynh_die
fi

conf=/etc/nginx/conf.d/$domain.d/$app.conf
if [ -f $conf ]; then
    echo "There is already a nginx conf file at this path: $conf " | sudo tee /dev/stderr
    ynh_die
fi

# Restore sources & data
sudo cp -a "./sources" $final_path

sudo chown www-data:www-data $final_path -R
sudo chmod 755 $final_path -R

# Restore conf files
sudo cp -a "./conf/nginx.conf" $conf

# Reload Nginx
sudo service nginx reload

# Set ssowat config
if [ "$is_public" = "Yes" ];
then
  ynh_app_setting_set $app unprotected_uris "/"
fi
