#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=3

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
path_url=$(ynh_app_setting_get --app=$app --key=path)
final_path=$(ynh_app_setting_get --app=$app --key=final_path) || ynh_die "This path already contains a folder"
phpversion=$(ynh_app_setting_get --app=$app --key=phpversion)

#=================================================
# CHECK VERSION
#=================================================

if ynh_compare_current_package_version --comparison lt --version 0.9.8.1~ynh1; then
  upgrade_type="0.9.8"
else
  upgrade_type=$(ynh_check_app_version_changed)
fi

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

# If final_path doesn't exist, create it
if [ -z "$final_path" ]; then
  final_path=/var/www/$app
  ynh_app_setting_set --app=$app --key=final_path --value=$final_path
fi

# Cleaning legacy permissions
if ynh_legacy_permissions_exists; then
  ynh_legacy_permissions_delete_all

  ynh_app_setting_delete --app=$app --key=is_public
fi

#=================================================
# Backup Data
#=================================================
ynh_script_progression --message="Backing up the data before upgrading (may take a while)..." --weight=30

bdd=$final_path/association.sqlite
squelettes=$final_path/www/squelettes

if  [ -d "$squelettes" ]; then
  cp -ar $squelettes /tmp/squelettes
fi

if [ -e "$bdd" ]; then
  cp -a $bdd /tmp/association.sqlite
fi

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================
ynh_script_progression --message="Backing up Garradin before upgrading (may take a while)..." --weight=30

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# restore it if the upgrade fails
	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors


#=================================================
# UPGRADE TO 0.9.8 if necessary
#=================================================

if [ "$upgrade_type" == "0.9.8" ]
then
  ynh_script_progression --message="Upgrading upgrade to 0.9.8" --weight=5
    # Download, check integrity, uncompress and patch the source from 0.9.8.src
  ynh_setup_source --dest_dir="$final_path" --source_id="0.9.8"
  # Set permissions on app files
  ynh_system_user_create --username=$app
  ynh_add_nginx_config
  ynh_add_fpm_config --package="$extra_php_dependencies"
  phpversion=$(ynh_app_setting_get --app=$app --key=phpversion)
  ynh_script_progression --message="restore data..." --weight=10

  backup_bdd=/tmp/association.sqlite
  backup_squelettes=/tmp/squelettes

  if 	[ -d "$backup_squelettes" ]
  then
    cp -ar $backup_squelettes $final_path/www/squelettes
    ynh_secure_remove  $backup_squelettes
  fi

  if [ -e "$backup_bdd" ]
  then
	  cp -a $backup_bdd $final_path/association.sqlite
    ynh_secure_remove $backup_bdd
  fi

  key=$(ynh_string_random --length=50)
  cp -a $final_path/config.dist.php $final_path/config.local.php
  ynh_replace_string --match_string="const SECRET_KEY = '3xUhIgGwuovRKOjVsVPQ5yUMfXUSIOX2GKzcebsz5OINrYC50r';" --replace_string="const SECRET_KEY = '$key';" --target_file="$final_path/config.local.php"
  if [ "$path_url" == "/" ]; then
  ynh_replace_string --match_string="//const WWW_URI = '/asso/';" --replace_string="const WWW_URI = '$path_url';" --target_file="$final_path/config.local.php"
  else
  ynh_replace_string --match_string="//const WWW_URI = '/asso/';" --replace_string="const WWW_URI = '$path_url/';" --target_file="$final_path/config.local.php"
  fi
  chown -R $app:$app $final_path
  chmod 755 $final_path
  # Create the visitors permission if needed
  if [ $is_public -eq 1 ]
  then
    ynh_permission_update --permission="main" --add="visitors"
  fi

  ynh_systemd_action --service_name=nginx --action=reload
  #finalyse upgrade
  ynh_local_curl "/index.php"
  sleep 5
  ynh_local_curl "/index.php"
  upgrade_type="UPGRADE_APP"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=5


if [ "$upgrade_type" == "UPGRADE_APP" ]
then
  # Download, check integrity, uncompress and patch the source from app.src
  ynh_setup_source --dest_dir="$final_path"
fi

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression --message="Making sure dedicated system user exists..." --weight=1

# Create a dedicated user (if not existing)
ynh_system_user_create --username=$app

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=2

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading PHP-FPM configuration..." --weight=2

# Create a dedicated PHP-FPM config
ynh_add_fpm_config --phpversion=$YNH_PHP_VERSION --package="$extra_php_dependencies"
phpversion=$(ynh_app_setting_get --app=$app --key=phpversion)

#=======================================================
# backup bdd, squelettes directory and config.local.php
#=======================================================
ynh_script_progression --message="restore data..." --weight=10

backup_bdd=/tmp/association.sqlite
backup_squelettes=/tmp/squelettes

if 	[ -d "$backup_squelettes" ]
then
  cp -ar $backup_squelettes $final_path/www/squelettes
  ynh_secure_remove  $backup_squelettes
fi

if [ -e "$backup_bdd" ]
then
	cp -a $backup_bdd $final_path/association.sqlite
  ynh_secure_remove $backup_bdd
fi

key=$(ynh_string_random --length=50)
cp -a $final_path/config.dist.php $final_path/config.local.php
ynh_replace_string --match_string="const SECRET_KEY = '3xUhIgGwuovRKOjVsVPQ5yUMfXUSIOX2GKzcebsz5OINrYC50r';" --replace_string="const SECRET_KEY = '$key';" --target_file="$final_path/config.local.php"
if [ "$path_url" == "/" ]; then
ynh_replace_string --match_string="//const WWW_URI = '/asso/';" --replace_string="const WWW_URI = '$path_url';" --target_file="$final_path/config.local.php"
else
ynh_replace_string --match_string="//const WWW_URI = '/asso/';" --replace_string="const WWW_URI = '$path_url/';" --target_file="$final_path/config.local.php"
fi

#=================================================
# Files owned by user app
#=================================================

# Set permissions on app files
chown -R $app:$app $final_path
chmod 400 config.dist.php config.local.php index.php sous-domaine.html VERSION
find $final_path/srcipts -type d -exec chmod 500 {} +
find $final_path/srcipts -type f -exec chmod 400 {} +
find $final_path/templates -type d -exec chmod 500 {} +
find $final_path/templates -type f -exec chmod 400 {} +
find $final_path/include -type d -exec chmod 500 {} +
find $final_path/include -type f -exec chmod 400 {} +
find $final_path/data -type d -exec chmod 700 {} +
find $final_path/data -type f -exec chmod 600 {} +
find /var/www/garradin/www -type d -exec chmod 755  {} +
find /var/www/garradin/www -type f -exec chmod 644  {} +
#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading NGINX web server..." --weight=1

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# Finalise Upgrade
#=================================================
ynh_script_progression --message="Finalise upgrade" --weight=1

ynh_local_curl "/admin/index.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of Garradin completed" --last
